const UIActionTypes = {
  OPEN_MENU: "OPEN_MENU",
  CLOSE_MENU: "CLOSE_MENU",
  OPEN_NOTIFICATION: "OPEN_NOTIFICATION",
  CLOSE_NOTIFICATION: "CLOSE_NOTIFICATION",
  OPEN_PROFILEMODAL: "OPEN_PROFILEMODAL",
  CLOSE_PROFILEMODAL: "CLOSE_PROFILEMODAL",
  OPEN_FEEDBACKMODAL: "OPEN_FEEDBACKMODAL",
  CLOSE_FEEDBACKMODAL: "CLOSE_FEEDBACKMODAL",
  OPEN_UPLOAD_MODAL: "OPEN_UPLOAD_MODAL",
  CLOSE_UPLOAD_MODAL: "CLOSE_UPLOAD_MODAL",
  OPEN_GOOGLE_MODAL: "OPEN_GOOGLE_MODAL",
  CLOSE_GOOGLE_MODAL: "CLOSE_GOOGLE_MODAL",
  OPEN_UPDATE_STUDENT_DETAILS_MODAL: "OPEN_UPDATE_STUDENT_DETAILS_MODAL",
  CLOSE_UPDATE_STUDENT_DETAILS_MODAL: "CLOSE_UPDATE_STUDENT_DETAILS_MODAL",
  SET_LOADING_TRUE: "SET_LOADING_TRUE",
  SET_LOADING_FALSE: "SET_LOADING_FALSE",
  SET_ROCKET_LOADING_TRUE: "SET_ROCKET_LOADING_TRUE",
  SET_ROCKET_LOADING_FALSE: "SET_ROCKET_LOADING_FALSE",
  SET_GREEN_LOADING_TRUE: "SET_GREEN_LOADING_TRUE",
  SET_GREEN_LOADING_FALSE: "SET_GREEN_LOADING_FALSE",
  SET_TOAST: "ALERT_MESSAGE",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  SET_WARNING_MESSAGE: "SET_WARNING_MESSAGE",
  SET_INFO_MESSAGE: "SET_INFO_MESSAGE",
  SET_SUCCESS_MESSAGE: "SET_SUCCESS_MESSAGE",
};

const userActionTypes = {
  AUTHENTICATE_USER: "AUTHENTICATE_USER",
  UNAUTHORIZE_USER: "UNAUTHORIZE_USER",
};

const ServerActionTypes = {
  GET_STUDENTS: "GET_STUDENTS",
  GET_SUBJECTS: "GET_SUBJECTS",
  GET_ATTENDANCE: "GET_ATTENDANCE",
  GET_ASSIGNMENT: "GET_ASSIGNMENT",
  GET_EXAMS: "GET_EXAMS",
  GET_HOLIDAYS: "GET_HOLIDAYS",
  GET_CLASSES: "GET_CLASSES",
  GET_BILLINGS: "GET_BILLINGS",
  GET_LATEST_LOGINS: "GET_LATEST_LOGINS",
  CLEAR_SERVER: "CLEAR_SERVER",
  UPLOAD_ASSIGNMENT: "UPLOAD_ASSIGNMENT",
  UPLOAD_EXAM: "UPLOAD_EXAM",
};

export { UIActionTypes, userActionTypes, ServerActionTypes };
